[tool.black]
target_version = ['py37']
# Keep exclude in sync with flake8 config in tox.ini
exclude = '''
/(
      \.git
    | \.tox
    | __pycache__
    | \.eggs
    | .*\.egg
    | .*\.egg-info
    | env
    | venv
    | \..*venv
)/
'''
